[shhs1]
source_edf_path = "C:\\Users\\forestjylee\\Developer\\PythonProject\\sleep_apnea_detection\\data\\shhs1\\source_edfs"
raw_data_path = "C:\\Users\\forestjylee\\Developer\\PythonProject\\sleep_apnea_detection\\data\\shhs1\\raw_data"
source_sleep_apnea_label_path = "C:\\Users\\forestjylee\\Developer\\PythonProject\\sleep_apnea_detection\\data\\shhs1\\source_labels"
sleep_apnea_label_path = "C:\\Users\\forestjylee\\Developer\\PythonProject\\sleep_apnea_detection\\data\\shhs1\\label_data"
samples_SA_intensity_info_filename = "shhs1_all_samples_SA_intensity_info.pkl"
train_data_path = "C:\\Users\\forestjylee\\Developer\\PythonProject\\sleep_apnea_detection\\data\\shhs1\\train_data"
validation_data_path = "C:\\Users\\forestjylee\\Developer\\PythonProject\\sleep_apnea_detection\\data\\shhs1\\validation_data"
test_data_path = "C:\\Users\\forestjylee\\Developer\\PythonProject\\sleep_apnea_detection\\data\\shhs1\\test_data"

[mesa]
source_edf_path = "C:\\Users\\forestjylee\\Developer\\PythonProject\\sleep_apnea_detection\\data\\mesa\\source_edfs"
raw_data_path = "C:\\Users\\forestjylee\\Developer\\PythonProject\\sleep_apnea_detection\\data\\mesa\\raw_data"
source_sleep_apnea_label_path = "C:\\Users\\forestjylee\\Developer\\PythonProject\\sleep_apnea_detection\\data\\mesa\\source_labels"
sleep_apnea_label_path = "C:\\Users\\forestjylee\\Developer\\PythonProject\\sleep_apnea_detection\\data\\mesa\\label_data"
samples_SA_intensity_info_filename = "mesa_all_samples_SA_intensity_info.pkl"
train_data_path = "C:\\Users\\forestjylee\\Developer\\PythonProject\\sleep_apnea_detection\\data\\mesa\\train_data"
validation_data_path = "C:\\Users\\forestjylee\\Developer\\PythonProject\\sleep_apnea_detection\\data\\mesa\\validation_data"
test_data_path = "C:\\Users\\forestjylee\\Developer\\PythonProject\\sleep_apnea_detection\\data\\mesa\\test_data"

[common_filepath]
output_root_folder = "C:\\Users\\forestjylee\\Developer\\PythonProject\\sleep_apnea_detection\\outputs"

[preprocess]
resample_rate = 10
window_length_secs = 10
window_slide_stride_secs = 4
sleep_apnea_overlap_length_secs = 4

low_pass_cutoff = 0.7
low_pass_filter_order = 2
high_pass_cutoff = 0.2
high_pass_filter_order = 2

[train]
trained_models_root_folder = "C:\\Users\\forestjylee\\Developer\\PythonProject\\sleep_apnea_detection\\trained_models"
model_name = "cnn_transformer"
class_num = 2
epochs = 10
batch_size = 128
learning_rate = 0.001
