shhs1_source_edf_path = "C:\\Users\\forestjylee\\Developer\\PythonProject\\sleep_apnea_detection\\data\\shhs1\\source_edfs"
shhs1_raw_data_path = "C:\\Users\\forestjylee\\Developer\\PythonProject\\sleep_apnea_detection\\data\\shhs1\\raw_data"
shhs1_source_sleep_apnea_label_path = "C:\\Users\\forestjylee\\Developer\\PythonProject\\sleep_apnea_detection\\data\\shhs1\\source_labels"
shhs1_sleep_apnea_label_path = "C:\\Users\\forestjylee\\Developer\\PythonProject\\sleep_apnea_detection\\data\\shhs1\\label_data"

mesa_source_edf_path = "C:\\Users\\forestjylee\\Developer\\PythonProject\\sleep_apnea_detection\\data\\mesa\\source_edfs"
mesa_raw_data_path = "C:\\Users\\forestjylee\\Developer\\PythonProject\\sleep_apnea_detection\\data\\mesa\\raw_data"
mesa_source_sleep_apnea_label_path = "C:\\Users\\forestjylee\\Developer\\PythonProject\\sleep_apnea_detection\\data\\mesa\\source_labels"
mesa_sleep_apnea_label_path = "C:\\Users\\forestjylee\\Developer\\PythonProject\\sleep_apnea_detection\\data\\mesa\\label_data"

train_data_path = "C:\\Users\\forestjylee\\Developer\\PythonProject\\sleep_apnea_detection\\data\\shhs1\\train_data"
validation_data_path = "C:\\Users\\forestjylee\\Developer\\PythonProject\\sleep_apnea_detection\\data\\shhs1\\validation_data"
test_data_path = "C:\\Users\\forestjylee\\Developer\\PythonProject\\sleep_apnea_detection\\data\\shhs1\\test_data"

output_root_folder = "C:\\Users\\forestjylee\\Developer\\PythonProject\\sleep_apnea_detection\\outputs"